name: GitHub for IT Pro CI/CD Pipeline
Env:

  OUTPUT_PATH: ${{ github.workspace }}
  on: [push]
  jobs:

# Deploy VM in Azure

  DeployVM:

    runs-on: windows-latest
    steps:

    # checkout code from repo

     - name: checkout repo

      uses: actions/checkout
      - name: look for ps1 file

      run: |

        ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'
        - name: provision virtual machine in azure

      env:

        RESOURCE_GROUP: rg-githubitpro

        RESOURCE_GROUP_REGION: southcentralus

        SERVER_NAME: gihtubactions

        ADMIN_LOGIN: testadmin

      run: >

        powershell -command "& 'D:\a\learning\learning\IaC\AzCLI\vmcreation.ps1' \
      -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }} \
      -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
      -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} \
      -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
      -resourceGroupName $env:RESOURCE_GROUP \
      -resourceGroupNameRegion $env:RESOURCE_GROUP_REGION \
      -serverName $env:SERVER_NAME \
      -adminLogin $env:ADMIN_LOGIN \
      -adminPassword ${{ secrets.ADMIN_PASSWORD }}"
