name: Azure VM - Add Disk and Resize

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  modify-vm:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        tenant-id: ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
        client-secret: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Add or Attach Disk to the VM
      shell: pwsh
      run: |
        # Set environment variables
        $env:RESOURCE_GROUP = "rg-githubitpro"
        $env:VM_NAME = "githubactions"
        $env:DISK_NAME = "$($env:VM_NAME)-additional-disk01"
        $env:DISK_SIZE = 128  # Size in GB

        # Check if the disk already exists
        $diskExists = az disk show --resource-group $env:RESOURCE_GROUP --name $env:DISK_NAME --query "id" --output tsv

        if ($diskExists) {
          Write-Host "Disk already exists. Attaching existing disk to the VM."
          az vm disk attach `
            --resource-group $env:RESOURCE_GROUP `
            --vm-name $env:VM_NAME `
            --name $env:DISK_NAME
        } else {
          Write-Host "Disk does not exist. Creating a new disk and attaching it to the VM."
          # Create a new managed disk
          az disk create `
            --resource-group $env:RESOURCE_GROUP `
            --name $env:DISK_NAME `
            --size-gb $env:DISK_SIZE `
            --sku Premium_LRS

          # Attach the new disk to the VM
          az vm disk attach `
            --resource-group $env:RESOURCE_GROUP `
            --vm-name $env:VM_NAME `
            --name $env:DISK_NAME
        }

    - name: Resize VM to increase memory
      shell: pwsh
      run: |
        # Set environment variables
        $env:RESOURCE_GROUP = "rg-githubitpro"
        $env:VM_NAME = "githubactions"
        $env:VM_SIZE = 'Standard_D4s_v3'  # Set new VM size

        # Resize the VM
        az vm resize `
          --resource-group $env:RESOURCE_GROUP `
          --name $env:VM_NAME `
          --size $env:VM_SIZE

    - name: Restart VM after resizing
      shell: pwsh
      run: |
        # Restart the VM after resizing
        az vm restart `
          --resource-group $env:RESOURCE_GROUP `
          --name $env:VM_NAME
