name: Azure VM Snapshot

on:
  

jobs:
  create-snapshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deallocate the VM (Optional but recommended)
      run: |
        az vm deallocate --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.VM_NAME }}

    - name: Get OS Disk ID
      id: get_os_disk
      run: |
        os_disk_id=$(az vm show \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.VM_NAME }} \
          --query "storageProfile.osDisk.managedDisk.id" \
          --output tsv)
        echo "::set-output name=os_disk_id::$os_disk_id"

    - name: Create Snapshot
      run: |
        az snapshot create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name "${{ secrets.VM_NAME }}-snapshot-$(date +%Y%m%d%H%M%S)" \
          --source ${{ steps.get_os_disk.outputs.os_disk_id }}

    - name: Start the VM (Optional)
      run: |
        az vm start --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.VM_NAME }}
