name: Azure VM Snapshot

on: [push]
permissions:
  id-token: write
  contents: read  # This is the minimum required to check out the repository
  
jobs:
  create-snapshot:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        tenant-id: ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
        client-secret: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Deallocate the VM (Optional but recommended)
      run: |
        az vm deallocate --resource-group rg-githubitpro --name githubactions

    - name: Get OS Disk ID
      id: get_os_disk
      run: |
        os_disk_id=$(az vm show \
          --resource-group rg-githubitpro \
          --name githubactions \
          --query "storageProfile.osDisk.managedDisk.id" \
          --output tsv)
        echo "::set-output name=os_disk_id::$os_disk_id"

    - name: Create Snapshot
      run: |
        az snapshot create \
          --resource-group rg-githubitpro \
          --name "githubactions-snapshot-$(date +%Y%m%d%H%M%S)" \
          --source ${{ steps.get_os_disk.outputs.os_disk_id }}

    - name: Start the VM (Optional)
      run: |
        az vm start --resource-group rg-githubitpro --name githubactions}
